f=open('student.txt','w')
print("Successfully Opened File..!!")
f.write('line1 \n')
f.write('line2 \n')
f.write('line3')
f.write('line4 \n')
f.writelines('This is an example 1 of an write line commands \n')
f.writelines('This is an example 2 of an write line commands \n')
f.close()
print("Data Write Successfully..!!")